services:
    classroom.service:
        class: SwivlClassroomBundle\Services\ClassroomService
        arguments:
            - "@doctrine.orm.entity_manager"

    classroom_controller.service:
        class: SwivlClassroomBundle\Controller\DefaultController
        arguments:
            - "@doctrine.orm.entity_manager"